---
title: "data import"
author: "Guangling Xu"
date: "9/17/2019"
output: github_document
---
```{r set up, include=FALSE}

library (tidyverse)

```


## load in dataset


```{r}
## reads in a dataset

litters_data = read_csv(file = "./FAS_litters.csv",
  skip = 10, col_names = FALSE)
litters_data
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

## load another dataset
```{r}
pups_data = read_csv(file = "./FAS_pups.csv")
```


## Parsing columns
```{r}
litters_data = read_csv(file = "./FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(), ##`means space
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```


## Read in an excel
```{r}
library(readxl)
mlb11_data = read_excel("./mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```


## load haven
```{r}
library(haven)
pulse_data = read_sas("./public_pulse_data.sas7bdat")
head(pulse_data, 5)
skimr::skim(pulse_data)
write_csv = (mlb11_data_subset, path ="./mlb_subset.csv" )
```


```


